### ISSUE TITLE
Kobo Aura HD resets after using file sharing

### ISSUE THREAD

**Issue by skinkie** [baskerville/plato#195] opened 2021-09-05 01:24 UTC
I have just used USB shared file storage via Plato. After unmounting and disconnecting the Kobo Aura HD resets into factory defaults. Hence, KMon etc. not being available anymore.

Another issue on the same device; When Plato quits via the Menu, and Nickel starts. A message appears stating the microSD card is not recognized, format it to FAT32 and try again.

**Comment by baskerville** [comment] 2021-09-05 07:37
> I have just used USB shared file storage via Plato. After unmounting and disconnecting the Kobo Aura HD resets into factory defaults. Hence, KMon etc. not being available anymore.

This is a duplicate of #190.

> Another issue on the same device; When Plato quits via the Menu, and Nickel starts. A message appears stating the microSD card is not recognized, format it to FAT32 and try again.

This appears to be a [benign message](https://www.mobileread.com/forums/showpost.php?p=3924645&postcount=480). Is the message also showing when using *KOReader*?

**Comment by skinkie** [comment] 2021-09-05 09:19
> > I have just used USB shared file storage via Plato. After unmounting and disconnecting the Kobo Aura HD resets into factory defaults. Hence, KMon etc. not being available anymore.
> 
> This is a duplicate of #190.

Thanks for the quick identification.


> > Another issue on the same device; When Plato quits via the Menu, and Nickel starts. A message appears stating the microSD card is not recognized, format it to FAT32 and try again.
> 
> This appears to be a [benign message](https://www.mobileread.com/forums/showpost.php?p=3924645&postcount=480). Is the message also showing when using _KOReader_?

No, with KOReader the application quits the three dotted screen appears, and Nickel launches without an incident.

**Comment by baskerville** [comment] 2021-09-08 09:47
> When Plato quits via the Menu, and Nickel starts. A message appears stating the microSD card is not recognized, format it to FAT32 and try again.

Could you try the [updated version of `nickel.sh`](https://github.com/baskerville/plato/blob/7ed671c8842e67322862fa15870e7c7cca266149/contrib/nickel.sh)?

**Comment by skinkie** [comment] 2021-09-08 09:52
> > When Plato quits via the Menu, and Nickel starts. A message appears stating the microSD card is not recognized, format it to FAT32 and try again.
> 
> Could you try the [updated version of `nickel.sh`](https://github.com/baskerville/plato/blob/7ed671c8842e67322862fa15870e7c7cca266149/contrib/nickel.sh)?

I guess I would have to do this via ssh?

**Comment by baskerville** [comment] 2021-09-08 09:59
> I guess I would have to do this via ssh?

If you've installed *Plato* using the one-click package, you can simply plug your device to a computer and overwrite `nickel.sh` in `.adds/plato`, on the SD card.

**Comment by skinkie** [comment] 2021-09-08 10:13
1. no fat32 error anymore
2. after unplug it is still going into the factory reset

**Comment by baskerville** [comment] 2021-09-08 10:33
> 1. no fat32 error anymore

Great.

> 2. after unplug it is still going into the factory reset, and now the factory reset is much worse, I have to set it up entirely again, including login

I'm afraid you'll have to overwrite `.adds/plato/scripts/{usb,wifi}-*.sh` with the latest versions of those scripts in this repository's `scripts` directory for this to be fixed. I thought you had done so, since I had mentioned the related issue.

**Comment by skinkie** [comment] 2021-09-08 11:15
Confirmed. After replacing the scripts, the e-reader goes back into Plato when the USB cable is disconnected. Issue can be closed if you are happy.

**Closed** 2021-09-08 11:54 UTC
