### ISSUE TITLE
Phantom book entries - have no way to clean up

### ISSUE THREAD

**Issue by patrick-tang** [baskerville/plato#151] opened 2021-01-17 16:59 UTC
Version: 0.9.13
Scenario: books get deleted through USB
Expected: the book entries in Plato can be removed manually or automatically
Actual: There will be phantom book entries in Plato and you cannot remove it manually - no error, just won't go

To be able to remove the phantom book entries from Plato, you have to copy back the books (if you still can find) then use "remove" function to remove.

Can we make the remove function simply clean up book entry if the book is not in Kobo any more?

**Comment by baskerville** [comment] 2021-01-17 17:57
There's a *Clean Up* entry in the *Database* submenu of the library menu: it has to be used carefully though. But I think the *clean up* action should, indeed, be executed each time the *import* action is triggered. This is a duplicate of #49.

**Closed** 2021-01-17 20:39 UTC

**Comment by patrick-tang** [comment] 2021-01-18 03:17
Thanks @baskerville .
I was not aware of such function and obviously I don't know enough about Plato - shame on me!
 But it would nicer when we try to delete an actually non-existing book the phantom entry could be deleted.
Unfortunately, I don't know Rust. Otherwise, I would try to contribute to help.

**Comment by baskerville** [comment] 2021-01-18 10:27
It should be the case as of 6584a6e42b1194b6f3d75e5f626effe57c24a88a.
