### ISSUE TITLE
[Feature Request] Page Mode besides Continuous

### ISSUE THREAD

**Issue by saisot2006** [baskerville/plato#260] opened 2022-09-01 15:09 UTC
I often read pdf file on Koreader with Page mode instead of Continuous. I found that Plato only supports Continuous. It would be perfect if Plato supports Page mode.
One more issue with Plato is the font size. Even though I increase the size to the maximum, it's still quite small and can't compare with the ones on Koreader or Nickel.

**Comment by baskerville** [comment] 2022-09-01 15:43
> I often read pdf file on Koreader with Page mode instead of Continuous. I found that Plato only supports Continuous. It would be perfect if Plato supports Page mode.

This is a duplicate of #252.

> One more issue with Plato is the font size. Even though I increase the size to the maximum, it's still quite small and can't compare with the ones on Koreader or Nickel.

The [relevant settings](https://github.com/baskerville/plato/blob/2e900ed3ff09bdb7237adc2e86109ab34b0d3963/contrib/Settings-sample.toml#L108-L111) are in *Settings.toml*.

**Comment by saisot2006** [comment] 2022-09-02 00:03
It would be nice to be able to change the option right in the app. One more thing Plato didn't show the cover of the book when my kobo went to sleep. It's a great function in default app/Koreader.

**Comment by baskerville** [comment] 2022-09-02 07:53
> One more thing Plato didn't show the cover of the book when my kobo went to sleep.

In the [*intermissions* section](https://github.com/baskerville/plato/blob/2e900ed3ff09bdb7237adc2e86109ab34b0d3963/contrib/Settings-sample.toml#L61-L68) of *Setttings.toml*: `suspend = "cover:"`.

**Closed** 2022-09-05 08:02 UTC
